name: issue_info_workflow

on: 
  issues:
    types: [ opened, reopened, labeled ]

jobs:
  
  autocoder-bot: 
    
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    
    steps:
      
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Generate Code with ChatGPT
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOCKEN_AUTOCODER }}
          REPOSITORY: ${{ github.repository }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_ASSIGNEES: ${{ join(github.event.issue.assignees.*.login, ', ') }}
          ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name) }}
        run: |
          echo "Issue #${{ env.ISSUE_NUMBER }}: '${{ env.ISSUE_TITLE }}'."
          echo "Labels: ${{ env.ISSUE_LABELS }}"
          echo "Assignees: ${{ env.ISSUE_ASSIGNEES }}"
          echo "Actions Repo Name: ${{ env.REPOSITORY }}"
          chmod +x ./scripts/script.sh
          ./scripts/script.sh ${{ env.GITHUB_TOKEN }} ${{ env.REPOSITORY }} ${{ env.ISSUE_NUMBER }} ${{ env.OPENAI_API_KEY }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: autocoder-artifact    # Name of the artifact
          path: .
      
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: autocoder-artifact    # Name of the artifact
          path: ./autocoder-artifact
      
      - name: Display Generated Code using the ls command
        run: ls -R ./autocoder-artifact | cat
        
