name: issue_info_workflow

on: 
  issues:
    type: [ opened, reopened ]

jobs:
  
  access_issue_info: 
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Print Issue Information
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_ASSIGNEES: ${{ join(github.event.issue.assignees.*.login, ', ') }}
          ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ', ') }}
        run: |
          echo "Issue Number: ${ISSUE_NUMBER}"
          echo "Issue Body: ${ISSUE_BODY}"
          echo "Issue Assignees: ${ISSUE_ASSIGNeES}"
          echo "Issue Labels: ${ISSUE_LABELS}"
