name: hello_workflow

on: [push]

jobs:
  say_hello: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Greeting Message
        run: echo  "Hello, world"
